### ISSUE TITLE
报错哦 nw.hashEvent is not a function

### ISSUE THREAD

**Issue by fants** [rozbo/node-noss#2]
> noss@1.0.0 start /root/test/node-noss
> node --no-warnings --loader ts-node/esm ./src/index.ts

[+0ms info]: started !
[+138ms info]: ws connected
[+2s info]: 获取区块完成,开始求解...hash:0xf1526ceee93e7b07f811bf2d80eaeeebbb7702316c9aed4a5f5d7a46d17f5004,block:167084692n

node:internal/event_target:1062
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: nw.hashEvent is not a function
    at cpuIntensiveFunction (file:///root/test/node-noss/src/worker.ts:28:23)
    at async file:///root/test/node-noss/src/worker.ts:41:5
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:314:10)
    at [kOnMessage] (node:internal/worker:325:37)
    at MessagePort.<anonymous> (node:internal/worker:225:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

**Comment by web3jt** [comment]
same

**Comment by 404huhu** [comment]
作者大佬，能解决一下吗，也是报这个问题，像是./api/nostr.js这个文件的问题

**Comment by jiushu666** [comment]
+1+1

**Comment by Arvinsmith2022** [comment]
+1

**Comment by dsky1990** [comment]
<img width="465" alt="image" src="https://github.com/rozbo/node-noss/assets/1579516/6e262b85-2262-4e53-b9f1-ade3a6a91436">

**Comment by flykye** [comment]
一样问题

**Comment by crazypol** [comment]
大佬解决下呗，都是这个问题
